
services:
  rnaseq:
    build: ./.local/container
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/workdir
    environment:
      - DISABLE_AUTH=true
    stdin_open: true
    tty: true
