


SLURM_CMD = srun 
SLURM_CMD += --partition=shared-cpu
SLURM_CMD += -n1 
SLURM_CMD += --cpus-per-task=4
SLURM_CMD += --time 2:00:00
SLURM_CMD += --mem=16G
SINGULARTY_SHELL = singularity exec 
SINGULARTY_SHELL += --bind /scratch:/tmp 
SINGULARTY_SHELL += --bind /acanas/m-BioinfoSupport 
SINGULARTY_SHELL += /acanas/m-BioinfoSupport/singularity/ngs_latest.sif 
SINGULARTY_SHELL += bash -c

export SHELL := $(SLURM_CMD) $(SINGULARTY_SHELL)

# PHONY rules with extension .ALL are run in the global bash
%.ALL:SHELL=bash


NJOB = 100
NCPU = 4

