
NJOB ?= 3
NCPU ?= 6
GENOMEDIR ?= ./data/ref
GENOME ?= Dd+Mm
BWAMEM_FLAGS ?= 


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Shortcuts
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
.PHONY:%.BWAMEM %/BWAMEM
%/BWAMEM:%/ $(GENOMEDIR)/$(GENOME)/genome.fasta
	find "$<" -maxdepth 1 -type f -name '*.fastq.gz' | sed 's/.fastq.gz$$/.BWAMEM/' | xargs $(MAKE) -j$(NJOB)

%.BWAMEM:%_R1.fastq.gz %_R2.fastq.gz
	$(MAKE) "$*.$(GENOME).bwamem.bam" "$*.$(GENOME).bwamem.bam.bai"

%.BWAMEM:%.fastq.gz
	$(MAKE) "$*.$(GENOME).bwamem.bam" "$*.$(GENOME).bwamem.bam.bai"

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# BWAMEM rules
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

# Paired-End mapping
.PRECIOUS:%.$(GENOME).bwamem.bam
%.$(GENOME).bwamem.bam:%_R1.fastq.gz %_R2.fastq.gz $(GENOMEDIR)/$(GENOME)/genome.fasta
	bwa mem $(BWAMEM_FLAGS) -t $(NCPU) '$(GENOMEDIR)/$(GENOME)/bwa_index/index' '$*_R1.fastq.gz' '$*_R2.fastq.gz' | samtools sort --threads $(NCPU) -o '$@' -

# Single-End mapping
.PRECIOUS:%.$(GENOME).bwamem.bam
%.$(GENOME).bwamem.bam:%.fastq.gz $(GENOMEDIR)/$(GENOME)/genome.fasta
	bwa mem $(BWAMEM_FLAGS) -t $(NCPU) '$(GENOMEDIR)/$(GENOME)/bwa_index/index' '$*.fastq.gz' | samtools sort --threads $(NCPU) -o '$@' -

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Imports
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
include $(LOCALDIR)/Makefile.samtools


