

NJOB ?= 3
NCPU ?= 6


.PHONY:%.bam.ALL
%.bam.ALL:%.bam
	$(MAKE) -j$(NJOB) "$<.bai" "$<.flagstat" "$<.cov.bed.bgz" "$<.start.bed.bgz"


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# SAMTOOLS rules
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.fasta.fai:%.fasta; samtools faidx "$<"
%.bam.bai:%.bam; samtools index "$<" 
%.bam.flagstat:%.bam; samtools flagstat "$<" > $@
%.bam.idxstat:%.bam; samtools idxstat "$<" > $@
%.unmap.fastq.gz:%.bam; samtools fastq -f4 "$<" | pigz > $@


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# BAM coverage
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.bam.cov.bed.bgz %.bam.cov.bed.bgz.tbi:%.bam
	#bam2cov --thread=$(NCPU) --out-prefix="$*.bam.cov" "$<"
%.bam.start.bed.bgz %.bam.start.bed.bgz.tbi:%.bam
	#bam2cov --thread=$(NCPU) --resize=1 --out-prefix="$*.bam.start" "$<"


