#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Set environment variables
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
MKDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
export LOCALDIR := $(MKDIR)/
export PATH := $(LOCALDIR)/bin/:$(PATH)

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Parameters
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
NCPU ?= 6
GENOMEDIR ?= ./data/ref
GENOME ?= Mm
HISAT2_FLAGS += --no-spliced-alignment
CUTADAPT_FLAGS += -e 0.05
CUTADAPT_FLAGS += --front CGGGGACTTATCAGCCAACCTGT
CUTADAPT_FLAGS += --minimum-length 25
CUTADAPT_FLAGS += --maximum-length 85


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Main
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
.PRECIOUS:%_cutadapt.fastq.gz %_umi.fastq.gz

.PHONY:%/TNSEQ.ALL
%/TNSEQ.ALL:INPUT_FQ = $(wildcard $*/*_R2.fastq.gz)
%/TNSEQ.ALL:%/ 
	$(MAKE) $(INPUT_FQ:%_R2.fastq.gz=%_umi.fastq.gz) $(INPUT_FQ:%_R2.fastq.gz=%_umi.TNSEQ.ALL)

.PHONY:%.TNSEQ.ALL
%.TNSEQ.ALL:%.fastq.gz 
	$(MAKE) $*.fastq.gz.ALL $*_cutadapt.fastq.gz $*_cutadapt.fastq.gz.fqchk $*_cutadapt.HT2.ALL $*_cutadapt.$(GENOME).ht2.bam.start.fwd.bw $*_cutadapt.$(GENOME).ht2.bam.start.rev.bw

#-#-#-#-#-#-#-#-#-#-#-#-#-#
# import external rules
#-#-#-#-#-#-#-#-#-#-#-#-#-#
include $(LOCALDIR)/Makefile.ref
include $(LOCALDIR)/Makefile.fastq
include $(LOCALDIR)/Makefile.ht2
include $(LOCALDIR)/Makefile.bam
include $(LOCALDIR)/Makefile.quantif



