

NJOB ?= 3
NCPU ?= 6


.PHONY:%.bam.ALL
%.bam.ALL:%.bam
	$(MAKE) -j$(NJOB) "$<.bai" "$<.flagstat" "$<.cov.fwd.bw" "$<.cov.rev.bw"


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# SAMTOOLS rules
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.fasta.fai:%.fasta; samtools faidx "$<"
%.bam.bai:%.bam; samtools index "$<" 
%.bam.flagstat:%.bam; samtools flagstat "$<" > $@
%.bam.idxstat:%.bam; samtools idxstat "$<" > $@
%.unmap.fastq.gz:%.bam; samtools fastq -f4 "$<" | pigz > $@


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# BAM coverage
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.bam.cov.bw:%.bam; bam_to_bw --thread=$(NCPU) --output="$@" "$<"
%.bam.cov.fwd.bw:%.bam; bam_to_bw --thread=$(NCPU) --output="$@" --strand="+" "$<"
%.bam.cov.rev.bw:%.bam; bam_to_bw --thread=$(NCPU) --output="$@" --strand="-" "$<"

%.bam.start.bw:%.bam; bam_to_bw --thread=$(NCPU) --output="$@" --resize=1 "$<"
%.bam.start.fwd.bw:%.bam; bam_to_bw --thread=$(NCPU) --output="$@" --strand="+" --resize=1 "$<"
%.bam.start.rev.bw:%.bam; bam_to_bw --thread=$(NCPU) --output="$@" --strand="-" --resize=1 "$<"

