
NCPU ?= 6
CUTADAPT_FLAGS ?= --adapter=AGATCGGAAGAGC --poly-a
# TruSeq adapter sequence read1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
# TruSeq adapter sequence read2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
# Nextera adapter sequence: CTGTCTCTTATACACATCT


.PHONY:%.fastq.gz.ALL
%.fastq.gz.ALL:%.fastq.gz 
	$(MAKE) $*.fastq.gz.fqchk $*.fastq.gz.fastqc.html

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# FASTQC
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.fastq.gz.fastqc.html:%.fastq.gz; fastqc --threads $(NCPU) '$<' && rm -f "$*_fastqc.zip"
%.fastq.gz.fqchk:%.fastq.gz; seqtk fqchk -q0 "$<" > "$@"


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# CUTADAPT
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%_cutadapt.fastq.gz %_cutadapt.json %_cutadapt.txt:%.fastq.gz
	cutadapt --cores $(NCPU) $(CUTADAPT_FLAGS) \
	  -o '$*_cutadapt.fastq.gz' \
	  --json='$*_cutadapt.json' '$<' \
	  --too-short-output '$*_cutadapt_short.fastq.gz' \
	  --too-long-output '$*_cutadapt_long.fastq.gz' \
	  > '$*_cutadapt.txt'


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# UMI
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Add READ2 sequence (=UMI sequence) to FASTQ header line (for UMI-tools)
%_umi.fastq.gz:%_R1.fastq.gz %_R2.fastq.gz
	seqtk mergepe $^ | fq_r2_to_r1_hdr | pigz > $@



