
NCPU ?= 6
GENOMEDIR ?= ./data/ref
GENOME ?= Mm
BWAMEM_FLAGS ?= 




#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# BWA-MEM PAIRED-END RULES 
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
.PHONY: %.BWAMEM.ALL
%.BWAMEM.ALL:%_R1.fastq.gz %_R2.fastq.gz
	$(MAKE) $*.$(GENOME).bwamem.bam $*.$(GENOME).bwamem.bam.ALL

.PRECIOUS:%.$(GENOME).bwamem.bam
%.$(GENOME).bwamem.bam:%_R1.fastq.gz %_R2.fastq.gz $(GENOMEDIR)/$(GENOME)/genome.fasta
	bwa mem $(BWAMEM_FLAGS) \
	  -t $(NCPU) \
	  $(GENOMEDIR)/$(GENOME)/bwa_index/index \
	  $*_R1.fastq.gz $*_R2.fastq.gz \
	| samtools sort --threads $(NCPU) -o '$@' -

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# BWA-MEM SINGLE-END RULES
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
.PHONY: %.BWAMEM.ALL
%.BWAMEM.ALL:%.fastq.gz
	$(MAKE) $*.$(GENOME).bwamem.bam $*.$(GENOME).bwamem.bam.ALL

.PRECIOUS:%.$(GENOME).bwamem.bam
%.$(GENOME).bwamem.bam:%.fastq.gz $(GENOMEDIR)/$(GENOME)/genome.fasta
	bwa mem $(BWAMEM_FLAGS) \
	  -t $(NCPU) \
	  $(GENOMEDIR)/$(GENOME)/bwa_index/index "$<" \
	| samtools sort --threads $(NCPU) -o '$@' -

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Imports
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
include $(LOCALDIR)/Makefile.bam


