#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Set environment variables
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
MKDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
export LOCALDIR := $(MKDIR)/
export PATH := $(LOCALDIR)/bin/:$(PATH)

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Parameters
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
NCPU ?= 6
GENOMEDIR ?= ./data/ref
GENOME ?= Mm
HISAT2_FLAGS += --no-spliced-alignment
CUTADAPT_FLAGS += -e 0.05
CUTADAPT_FLAGS += --front CGGGGACTTATCAGCCAACCTGT
CUTADAPT_FLAGS += --minimum-length 25
CUTADAPT_FLAGS += --maximum-length 85


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Main
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
.PHONY:%/TNSEQ.ALL
%/TNSEQ.ALL:INPUT_FQ = $(wildcard $*/*_R2.fastq.gz)
%/TNSEQ.ALL:%/
	$(MAKE) $(INPUT_FQ:%_R2.fastq.gz=%_umi.fastq.gz) $(INPUT_FQ:%_R2.fastq.gz=%_umi.TNSEQ.ALL)
	#$(MAKE) $*/TNSEQ_QUANTIFY.ALL

.PHONY:%.TNSEQ.ALL
%.TNSEQ.ALL:%.fastq.gz %.fastq.gz.ALL %_cutadapt.fastq.gz %_cutadapt.HT2.ALL; echo "DONE: $@"

#-#-#-#-#-#-#-#-#-#-#-#-#-#
# import external rules
#-#-#-#-#-#-#-#-#-#-#-#-#-#
include $(LOCALDIR)/Makefile.ref
include $(LOCALDIR)/Makefile.fastq
include $(LOCALDIR)/Makefile.ht2
include $(LOCALDIR)/Makefile.bam
include $(LOCALDIR)/Makefile.quantif



