
NCPU ?= 6

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# SAMTOOLS rules
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.fasta.fai:%.fasta; samtools faidx "$<"
%.bam.bai:%.bam; samtools index "$<" 
%.bam.flagstat:%.bam; samtools flagstat "$<" > $@
%.bam.idxstat:%.bam; samtools idxstat "$<" > $@
%.unmap.fastq.gz:%.bam; samtools fastq -f4 "$<" | pigz > $@



#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# BAM coverage
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.cov.bed.bgz %.cov.bed.bgz.tbi:%.bam
	bam2cov --thread $(NCPU) --out-prefix="$*.cov" "$<"

%.start.bed.bgz %.start.bed.bgz.tbi:%.bam
#	bam2cov --thread $(NCPU) --out-prefix="$*.cov" "$<"


