#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Set environment variables
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
MKDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
export LOCALDIR := $(MKDIR)/
export PATH := $(LOCALDIR)/bin/:$(PATH)

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Parameters
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
NCPU ?= 6
GENOMEDIR ?= ./data/ref
GENOME ?= Mm

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Main
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
.PHONY:%/RNASEQ.ALL
%/RNASEQ.ALL:INPUT_FQ = $(wildcard $*/*.fastq.gz)
%/RNASEQ.ALL:%/
	$(MAKE) $(INPUT_FQ:%.fastq.gz=%.RNASEQ.ALL)
	$(MAKE) $*/HT2_QUANTIFY.ALL

.PHONY:%.RNASEQ.ALL
%.RNASEQ.ALL:%.fastq.gz
	$(MAKE) $<.ALL $*.HT2.ALL


#-#-#-#-#-#-#-#-#-#-#-#-#-#
# import external rules
#-#-#-#-#-#-#-#-#-#-#-#-#-#
include $(LOCALDIR)/Makefile.ref
include $(LOCALDIR)/Makefile.fastq
include $(LOCALDIR)/Makefile.ht2
include $(LOCALDIR)/Makefile.bam
include $(LOCALDIR)/Makefile.quantif



